# action.yml
name: 'Pack Docker Action'
description: 'Run the Cloud Native Buildpacks Pack CLI'
author: 'dfreilich'
branding:
  color: blue
  icon: layers   # from https://feathericons.com/

inputs:
  args:
    description: Arguments for pack
    required: true
  username:
    description: Username used to log in to a Docker registry. If not set, then no login will occur
    required: false
  password:
    description: Password or personal access token used to log in to a Docker registry. If not set, then no login will occur
    required: false
  registry:
    description: Server address of Docker registry. If not set then will default to Docker Hub
    required: false

runs:
  using: "composite"
  steps:
    - id: install
      uses: buildpacks/github-actions/setup-pack@v4.1.0
    - id: cleanup
      shell: bash
      run: |
        rm "${HOME}"/bin/jq
        rm "${HOME}"/bin/crane
        rm "${HOME}"/bin/yj
    - id: login
      shell: bash
      run: |
        if [ -n "${INPUT_USERNAME}" ] && [ -n "${INPUT_PASSWORD}" ]; then
          echo "${INPUT_PASSWORD}" | docker login -u "${INPUT_USERNAME}" --password-stdin "${INPUT_REGISTRY}"
        fi
    - id: run-pack
      shell: bash
      run: |
        pack ${{ inputs.args }}
