name: autorelease

on:
  workflow_run:
    workflows: ["automerge"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      tag_name:
        description: The release tag to distribute. If empty, it will bump the latest version.

jobs:
  release-and-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: last-version
        uses: actions/github-script@v3
        id: version
        with:
          result-encoding: string
          script: |
            let tag = (context.payload.inputs && context.payload.inputs.tag_name)
              || (await github.repos.getLatestRelease({owner: context.repo.owner,repo: context.repo.repo})).data.data.name

            if (!tag) {
              throw "ERROR: unable to determine tag";
            }

            return tag.replace(/^v/, '');
      - name: Bump Release
        id: bump-version
        run: |
          v=${{ steps.version.outputs.result }}
          bump=$(echo "${v%.*}.$((${v##*.}+1))")
          major=$(echo "${v%.*.*}")
          echo "ACTION_TAG=v${bump}" >> $GITHUB_ENV
          echo "MAJOR_TAG=v${major}" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.ACTION_TAG }}
          body: |
            # pack-action ${{ env.ACTION_TAG }}
            This is an automated release of the Pack Action, incorporating a dependency update. For detailed usage
            documentation, check out the v1.0 release notes [here](https://github.com/dfreilich/pack-action/releases/tag/v1.0)
            or the documentation [here](https://github.com/dfreilich/pack-action#usage)
      - name: Update major tag
        run: |
          git tag ${{ env.MAJOR_TAG }}
          git push origin ${{ env.MAJOR_TAG }}
