name: test

on: [push, pull_request]

env:
  TEST_APP_PATH: ".github/workflows/test-app"
  BUILDER: "paketobuildpacks/builder:tiny"

jobs:
  help:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pack Help
        uses: ./
        with:
          args: 'help'
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pack Version
        uses: ./
        with:
          args: 'version'
  local_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2
      - name: Pack Build
        uses: ./
        with:
          args: 'build test_img --builder ${{ env.BUILDER }} --path ${{ env.TEST_APP_PATH }}'
      - name: Test App
        run: |
          docker run -d -p 8080:8080 --name testapp test_img
          curl localhost:8080
      - name: Pack Rebase
        uses: ./
        with:
          args: 'rebase test_img'
      - name: Inspect Image
        uses: ./
        with:
          args: 'inspect-image test_img'
      - name: Clean Up
        run: |
          docker container stop testapp
