name: test

on: [push]

env:
  TEST_APP_PATH: ".github/workflows/test-app"
  BUILDER: "paketobuildpacks/builder:tiny"

jobs:
#  test_pack_help:
#    runs-on: ubuntu-latest
#    name: Pack Help
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Pack Help
#        uses: ./
#        with:
#          args: 'help'
#  test_pack_version:
#    runs-on: ubuntu-latest
#    name: Pack Version
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Pack Version
#        uses: ./
#        with:
#          args: 'version'
  test_pack_build:
    runs-on: ubuntu-latest
    name: Pack Build
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2
      - name: Run local registry
        run: docker run -d -p 5000:5000 registry:2
      - name: Pack Build
        uses: ./
        with:
          args: 'localhost:5000/test --path ${{ env.TEST_APP_PATH }} --builder ${{ env.BUILDER }}'
