name: test

on: [push]

env:
  TEST_APP_PATH: ".github/workflows/test-app"
  BUILDER: "paketobuildpacks/builder:tiny"
  TEST_RUN_IMG: "paketobuildpacks/run:base-cnb"

jobs:
  help:
    runs-on: ubuntu-latest
    name: Pack Help
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pack Help
        uses: ./
        with:
          args: 'help'
  version:
    runs-on: ubuntu-latest
    name: Pack Version
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pack Version
        uses: ./
        with:
          args: 'version'
  local_build:
    runs-on: ubuntu-latest
    name: Pack Local Build
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2
      - name: Pack Build
        uses: ./
        with:
          args: 'build test --builder ${{ env.BUILDER }} --path ${{ env.TEST_APP_PATH }}'
      - name: Test App
        run: |
          docker run -d -p 8080:8080 --name testapp test
          curl localhost:8080
      - name: Pack Rebase
        uses: ./
        with:
          args: 'rebase test --run-image ${{ env.TEST_RUN_IMG }}'
      - name: Inspect Image
        uses: ./
        with:
          args: 'inspect-image test'
      - name: Clean Up
        run: |
          docker container stop testapp
